### ISSUE TITLE
Czyżyny, not Czyyny

### ISSUE THREAD

**Issue by matkoniecz** [whosonfirst-data/whosonfirst-data#1022]
Czyyny label is result of UTF-8 support missing in source of labels - what gives poor results in Poland
Czyżyny labels is a correct label from OSM data.

![selection_003](https://user-images.githubusercontent.com/899988/32135328-5e72aa14-bbfd-11e7-8719-a63a6d9f082d.png)

https://mapzen.com/tangram/play/?#15.7500/50.0735/20.0073 with

```
global:
    name_source: |
        function() {
            return feature['name:pl'] || feature.name;
        }
    text_stroke: '#e4e1de'
    text_font_family: 'Open Sans'
    text_fill_color: black
    earth_color: '#faf4f4'

sources:
    mapzen:
        type: TopoJSON #GeoJSON, MVT, TopoJSON
        url:  https://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.topojson
        max_zoom: 20

camera:
    type: isometric


fonts:
    Open Sans:
        - weight: 300 # Light
          url: fonts/OpenSans-Light.woff
        - weight: normal # Regular
          url: fonts/OpenSans-Regular.woff
        - weight: normal # Regular
          style: italic
          url: fonts/OpenSans-Italic.woff
        - weight: 600 # Semi Bold
          url: fonts/OpenSans-Semibold.woff
        - weight: 600 # Semi Bold
          style: italic
          url: fonts/OpenSans-SemiboldItalic.woff
        - weight: bold
          url: fonts/OpenSans-Bold.woff

scene:
    background:
        color: global.earth_color

layers:
    roads:
        data: { source: mapzen, layer: roads }
        filter: { not: { kind_detail: service, kind: rail } }
        highway:
            draw:
                lines:
                    order: 1012
                    color: white
                    cap: round
                    width: [[1, 1.5px], [14, 2.5px], [16, 2.5px], [19, 6m]]
                    outline:
                        order: 1010
                        color: '#9370db'
                        width: [[14, 1px], [15, 1.5px]]
                        cap: butt
    places:
        data: { source: mapzen }
        draw:
            text:
                text_source: global.name_source
                font:
                    weight: 100
                    size: 13px
                    family: global.text_font_family
                    fill: global.text_fill_color
                    stroke: { color: global.text_stroke, width: [[1,2px], [12,3px],[16,4px]] }

```
